server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh  #payment_route   路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE    #匹配提供服务后的路由地址
          predicates:
              - Path=/payment/get/** #断言，路径相匹配的进行路由
              - After=2021-05-21T11:00:47.425813700+08:00[Asia/Shanghai]
              - Cookie=username,zzyy
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE    #匹配提供服务后的路由地址
          predicates:
            - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:   #将Gateway注册进eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
config:
  inf: 66666
